---
swagger: "2.0"
info:
  x-ibm-name: "xmltojson"
  title: "xmltojson"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/xmltojson"
consumes:
- "application/xml"
produces:
- "application/json"
security:
- api-key-2: []
  api-key-1: []
securityDefinitions:
  api-key-2:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Secret"
  api-key-1:
    type: "apiKey"
    description: ""
    in: "header"
    name: "X-IBM-Client-Id"
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - xml-to-json:
        title: "xml-to-json"
        version: "1.0.0"
  gateway: "datapower-gateway"
  phase: "realized"
paths:
  /path-1:
    parameters:
    - $ref: "#/parameters/xmltojson"
    post:
      responses:
        200:
          description: "200 OK"
tags: []
parameters:
  xmltojson:
    name: "xmltojson"
    required: true
    in: "body"
    schema:
      type: "object"
    description: "xmltojson"