swagger: '2.0'
info:
  title: Message
  x-ibm-name: message-api
  version: 1.0.0
host: $(catalog.host)
schemes:
  - https
basePath: /public
produces:
  - application/json
security: []
securityDefinitions:
  
